In [14]:
from datetime import datetime, timedelta, tzinfo
import pandas as pd
import os
from gtrend import Trends, calculate_search_granularity, get_index_granularity
from dateutil.parser import parse

In [ ]:
dates = pd.date_range(start="2023-01-01", periods=7, freq='D')
print(dates)
df = pd.DataFrame(0, index=dates, columns=['test'])
print(df)
granularity = get_index_granularity(df.index)
print(granularity)
g2 = calculate_search_granularity("2023-01-01", "2023-09-28")
print(g2)

In [6]:
t=Trends(verbose=True)
t._search_serpapi('bathroom', '2004-01-01 2025-01-01')

Sending SerpAPI search request:
  Search term: bathroom
  Time range: 2004-01-01 2025-01-01

{'search_metadata': {'id': '6837f30e5e34942bc516c095',
  'status': 'Success',
  'json_endpoint': 'https://serpapi.com/searches/7306eef1a342dda7/6837f30e5e34942bc516c095.json',
  'created_at': '2025-05-29 05:39:26 UTC',
  'processed_at': '2025-05-29 05:39:26 UTC',
  'google_trends_url': 'https://trends.google.com/trends/embed/explore/TIMESERIES?hl=en&tz=420&req=%7B%22comparisonItem%22%3A%5B%7B%22keyword%22%3A%22bathroom%22%2C%22geo%22%3A%22US%22%2C%22time%22%3A%222004-01-01+2025-01-01%22%7D%5D%2C%22category%22%3A%220%22%2C%22property%22%3A%22%22%7D',
  'raw_html_file': 'https://serpapi.com/searches/7306eef1a342dda7/6837f30e5e34942bc516c095.html',
  'prettify_html_file': 'https://serpapi.com/searches/7306eef1a342dda7/6837f30e5e34942bc516c095.prettify',
  'total_time_taken': 3.78},
 'search_parameters': {'engine': 'google_trends',
  'q': 'bathroom',
  'hl': 'en',
  'geo': 'US',
  'cat': '0',
  'date': '2004-01-01 2025-01-01',
  'tz': '420',
  'data_type': 'TIMESERIES'},
 'interest_over_time': {'timeline_data': [{'date': 'Jan 2004',
    'timestamp': '1072915200',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Feb 2004',
    'timestamp': '1075593600',
    'values': [{'query': 'bathroom', 'value': '44', 'extracted_value': 44}]},
   {'date': 'Mar 2004',
    'timestamp': '1078099200',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Apr 2004',
    'timestamp': '1080777600',
    'values': [{'query': 'bathroom', 'value': '37', 'extracted_value': 37}]},
   {'date': 'May 2004',
    'timestamp': '1083369600',
    'values': [{'query': 'bathroom', 'value': '39', 'extracted_value': 39}]},
   {'date': 'Jun 2004',
    'timestamp': '1086048000',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'Jul 2004',
    'timestamp': '1088640000',
    'values': [{'query': 'bathroom', 'value': '48', 'extracted_value': 48}]},
   {'date': 'Aug 2004',
    'timestamp': '1091318400',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Sep 2004',
    'timestamp': '1093996800',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Oct 2004',
    'timestamp': '1096588800',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Nov 2004',
    'timestamp': '1099267200',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Dec 2004',
    'timestamp': '1101859200',
    'values': [{'query': 'bathroom', 'value': '37', 'extracted_value': 37}]},
   {'date': 'Jan 2005',
    'timestamp': '1104537600',
    'values': [{'query': 'bathroom', 'value': '50', 'extracted_value': 50}]},
   {'date': 'Feb 2005',
    'timestamp': '1107216000',
    'values': [{'query': 'bathroom', 'value': '48', 'extracted_value': 48}]},
   {'date': 'Mar 2005',
    'timestamp': '1109635200',
    'values': [{'query': 'bathroom', 'value': '48', 'extracted_value': 48}]},
   {'date': 'Apr 2005',
    'timestamp': '1112313600',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'May 2005',
    'timestamp': '1114905600',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Jun 2005',
    'timestamp': '1117584000',
    'values': [{'query': 'bathroom', 'value': '44', 'extracted_value': 44}]},
   {'date': 'Jul 2005',
    'timestamp': '1120176000',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Aug 2005',
    'timestamp': '1122854400',
    'values': [{'query': 'bathroom', 'value': '46', 'extracted_value': 46}]},
   {'date': 'Sep 2005',
    'timestamp': '1125532800',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Oct 2005',
    'timestamp': '1128124800',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Nov 2005',
    'timestamp': '1130803200',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Dec 2005',
    'timestamp': '1133395200',
    'values': [{'query': 'bathroom', 'value': '37', 'extracted_value': 37}]},
   {'date': 'Jan 2006',
    'timestamp': '1136073600',
    'values': [{'query': 'bathroom', 'value': '50', 'extracted_value': 50}]},
   {'date': 'Feb 2006',
    'timestamp': '1138752000',
    'values': [{'query': 'bathroom', 'value': '46', 'extracted_value': 46}]},
   {'date': 'Mar 2006',
    'timestamp': '1141171200',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Apr 2006',
    'timestamp': '1143849600',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'May 2006',
    'timestamp': '1146441600',
    'values': [{'query': 'bathroom', 'value': '39', 'extracted_value': 39}]},
   {'date': 'Jun 2006',
    'timestamp': '1149120000',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'Jul 2006',
    'timestamp': '1151712000',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Aug 2006',
    'timestamp': '1154390400',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Sep 2006',
    'timestamp': '1157068800',
    'values': [{'query': 'bathroom', 'value': '46', 'extracted_value': 46}]},
   {'date': 'Oct 2006',
    'timestamp': '1159660800',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Nov 2006',
    'timestamp': '1162339200',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'Dec 2006',
    'timestamp': '1164931200',
    'values': [{'query': 'bathroom', 'value': '35', 'extracted_value': 35}]},
   {'date': 'Jan 2007',
    'timestamp': '1167609600',
    'values': [{'query': 'bathroom', 'value': '50', 'extracted_value': 50}]},
   {'date': 'Feb 2007',
    'timestamp': '1170288000',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Mar 2007',
    'timestamp': '1172707200',
    'values': [{'query': 'bathroom', 'value': '48', 'extracted_value': 48}]},
   {'date': 'Apr 2007',
    'timestamp': '1175385600',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'May 2007',
    'timestamp': '1177977600',
    'values': [{'query': 'bathroom', 'value': '40', 'extracted_value': 40}]},
   {'date': 'Jun 2007',
    'timestamp': '1180656000',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Jul 2007',
    'timestamp': '1183248000',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Aug 2007',
    'timestamp': '1185926400',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Sep 2007',
    'timestamp': '1188604800',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Oct 2007',
    'timestamp': '1191196800',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Nov 2007',
    'timestamp': '1193875200',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Dec 2007',
    'timestamp': '1196467200',
    'values': [{'query': 'bathroom', 'value': '37', 'extracted_value': 37}]},
   {'date': 'Jan 2008',
    'timestamp': '1199145600',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Feb 2008',
    'timestamp': '1201824000',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Mar 2008',
    'timestamp': '1204329600',
    'values': [{'query': 'bathroom', 'value': '52', 'extracted_value': 52}]},
   {'date': 'Apr 2008',
    'timestamp': '1207008000',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'May 2008',
    'timestamp': '1209600000',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Jun 2008',
    'timestamp': '1212278400',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'Jul 2008',
    'timestamp': '1214870400',
    'values': [{'query': 'bathroom', 'value': '44', 'extracted_value': 44}]},
   {'date': 'Aug 2008',
    'timestamp': '1217548800',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Sep 2008',
    'timestamp': '1220227200',
    'values': [{'query': 'bathroom', 'value': '38', 'extracted_value': 38}]},
   {'date': 'Oct 2008',
    'timestamp': '1222819200',
    'values': [{'query': 'bathroom', 'value': '39', 'extracted_value': 39}]},
   {'date': 'Nov 2008',
    'timestamp': '1225497600',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'Dec 2008',
    'timestamp': '1228089600',
    'values': [{'query': 'bathroom', 'value': '37', 'extracted_value': 37}]},
   {'date': 'Jan 2009',
    'timestamp': '1230768000',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Feb 2009',
    'timestamp': '1233446400',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Mar 2009',
    'timestamp': '1235865600',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Apr 2009',
    'timestamp': '1238544000',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'May 2009',
    'timestamp': '1241136000',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'Jun 2009',
    'timestamp': '1243814400',
    'values': [{'query': 'bathroom', 'value': '44', 'extracted_value': 44}]},
   {'date': 'Jul 2009',
    'timestamp': '1246406400',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Aug 2009',
    'timestamp': '1249084800',
    'values': [{'query': 'bathroom', 'value': '46', 'extracted_value': 46}]},
   {'date': 'Sep 2009',
    'timestamp': '1251763200',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Oct 2009',
    'timestamp': '1254355200',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Nov 2009',
    'timestamp': '1257033600',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Dec 2009',
    'timestamp': '1259625600',
    'values': [{'query': 'bathroom', 'value': '37', 'extracted_value': 37}]},
   {'date': 'Jan 2010',
    'timestamp': '1262304000',
    'values': [{'query': 'bathroom', 'value': '50', 'extracted_value': 50}]},
   {'date': 'Feb 2010',
    'timestamp': '1264982400',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Mar 2010',
    'timestamp': '1267401600',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Apr 2010',
    'timestamp': '1270080000',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'May 2010',
    'timestamp': '1272672000',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Jun 2010',
    'timestamp': '1275350400',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'Jul 2010',
    'timestamp': '1277942400',
    'values': [{'query': 'bathroom', 'value': '41', 'extracted_value': 41}]},
   {'date': 'Aug 2010',
    'timestamp': '1280620800',
    'values': [{'query': 'bathroom', 'value': '40', 'extracted_value': 40}]},
   {'date': 'Sep 2010',
    'timestamp': '1283299200',
    'values': [{'query': 'bathroom', 'value': '38', 'extracted_value': 38}]},
   {'date': 'Oct 2010',
    'timestamp': '1285891200',
    'values': [{'query': 'bathroom', 'value': '37', 'extracted_value': 37}]},
   {'date': 'Nov 2010',
    'timestamp': '1288569600',
    'values': [{'query': 'bathroom', 'value': '37', 'extracted_value': 37}]},
   {'date': 'Dec 2010',
    'timestamp': '1291161600',
    'values': [{'query': 'bathroom', 'value': '33', 'extracted_value': 33}]},
   {'date': 'Jan 2011',
    'timestamp': '1293840000',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Feb 2011',
    'timestamp': '1296518400',
    'values': [{'query': 'bathroom', 'value': '48', 'extracted_value': 48}]},
   {'date': 'Mar 2011',
    'timestamp': '1298937600',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Apr 2011',
    'timestamp': '1301616000',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'May 2011',
    'timestamp': '1304208000',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Jun 2011',
    'timestamp': '1306886400',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Jul 2011',
    'timestamp': '1309478400',
    'values': [{'query': 'bathroom', 'value': '46', 'extracted_value': 46}]},
   {'date': 'Aug 2011',
    'timestamp': '1312156800',
    'values': [{'query': 'bathroom', 'value': '46', 'extracted_value': 46}]},
   {'date': 'Sep 2011',
    'timestamp': '1314835200',
    'values': [{'query': 'bathroom', 'value': '43', 'extracted_value': 43}]},
   {'date': 'Oct 2011',
    'timestamp': '1317427200',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Nov 2011',
    'timestamp': '1320105600',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Dec 2011',
    'timestamp': '1322697600',
    'values': [{'query': 'bathroom', 'value': '40', 'extracted_value': 40}]},
   {'date': 'Jan 2012',
    'timestamp': '1325376000',
    'values': [{'query': 'bathroom', 'value': '52', 'extracted_value': 52}]},
   {'date': 'Feb 2012',
    'timestamp': '1328054400',
    'values': [{'query': 'bathroom', 'value': '52', 'extracted_value': 52}]},
   {'date': 'Mar 2012',
    'timestamp': '1330560000',
    'values': [{'query': 'bathroom', 'value': '48', 'extracted_value': 48}]},
   {'date': 'Apr 2012',
    'timestamp': '1333238400',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'May 2012',
    'timestamp': '1335830400',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Jun 2012',
    'timestamp': '1338508800',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Jul 2012',
    'timestamp': '1341100800',
    'values': [{'query': 'bathroom', 'value': '51', 'extracted_value': 51}]},
   {'date': 'Aug 2012',
    'timestamp': '1343779200',
    'values': [{'query': 'bathroom', 'value': '50', 'extracted_value': 50}]},
   {'date': 'Sep 2012',
    'timestamp': '1346457600',
    'values': [{'query': 'bathroom', 'value': '47', 'extracted_value': 47}]},
   {'date': 'Oct 2012',
    'timestamp': '1349049600',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Nov 2012',
    'timestamp': '1351728000',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Dec 2012',
    'timestamp': '1354320000',
    'values': [{'query': 'bathroom', 'value': '42', 'extracted_value': 42}]},
   {'date': 'Jan 2013',
    'timestamp': '1356998400',
    'values': [{'query': 'bathroom', 'value': '54', 'extracted_value': 54}]},
   {'date': 'Feb 2013',
    'timestamp': '1359676800',
    'values': [{'query': 'bathroom', 'value': '53', 'extracted_value': 53}]},
   {'date': 'Mar 2013',
    'timestamp': '1362096000',
    'values': [{'query': 'bathroom', 'value': '55', 'extracted_value': 55}]},
   {'date': 'Apr 2013',
    'timestamp': '1364774400',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'May 2013',
    'timestamp': '1367366400',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Jun 2013',
    'timestamp': '1370044800',
    'values': [{'query': 'bathroom', 'value': '51', 'extracted_value': 51}]},
   {'date': 'Jul 2013',
    'timestamp': '1372636800',
    'values': [{'query': 'bathroom', 'value': '56', 'extracted_value': 56}]},
   {'date': 'Aug 2013',
    'timestamp': '1375315200',
    'values': [{'query': 'bathroom', 'value': '56', 'extracted_value': 56}]},
   {'date': 'Sep 2013',
    'timestamp': '1377993600',
    'values': [{'query': 'bathroom', 'value': '53', 'extracted_value': 53}]},
   {'date': 'Oct 2013',
    'timestamp': '1380585600',
    'values': [{'query': 'bathroom', 'value': '51', 'extracted_value': 51}]},
   {'date': 'Nov 2013',
    'timestamp': '1383264000',
    'values': [{'query': 'bathroom', 'value': '51', 'extracted_value': 51}]},
   {'date': 'Dec 2013',
    'timestamp': '1385856000',
    'values': [{'query': 'bathroom', 'value': '45', 'extracted_value': 45}]},
   {'date': 'Jan 2014',
    'timestamp': '1388534400',
    'values': [{'query': 'bathroom', 'value': '58', 'extracted_value': 58}]},
   {'date': 'Feb 2014',
    'timestamp': '1391212800',
    'values': [{'query': 'bathroom', 'value': '57', 'extracted_value': 57}]},
   {'date': 'Mar 2014',
    'timestamp': '1393632000',
    'values': [{'query': 'bathroom', 'value': '58', 'extracted_value': 58}]},
   {'date': 'Apr 2014',
    'timestamp': '1396310400',
    'values': [{'query': 'bathroom', 'value': '51', 'extracted_value': 51}]},
   {'date': 'May 2014',
    'timestamp': '1398902400',
    'values': [{'query': 'bathroom', 'value': '53', 'extracted_value': 53}]},
   {'date': 'Jun 2014',
    'timestamp': '1401580800',
    'values': [{'query': 'bathroom', 'value': '56', 'extracted_value': 56}]},
   {'date': 'Jul 2014',
    'timestamp': '1404172800',
    'values': [{'query': 'bathroom', 'value': '58', 'extracted_value': 58}]},
   {'date': 'Aug 2014',
    'timestamp': '1406851200',
    'values': [{'query': 'bathroom', 'value': '60', 'extracted_value': 60}]},
   {'date': 'Sep 2014',
    'timestamp': '1409529600',
    'values': [{'query': 'bathroom', 'value': '54', 'extracted_value': 54}]},
   {'date': 'Oct 2014',
    'timestamp': '1412121600',
    'values': [{'query': 'bathroom', 'value': '53', 'extracted_value': 53}]},
   {'date': 'Nov 2014',
    'timestamp': '1414800000',
    'values': [{'query': 'bathroom', 'value': '54', 'extracted_value': 54}]},
   {'date': 'Dec 2014',
    'timestamp': '1417392000',
    'values': [{'query': 'bathroom', 'value': '49', 'extracted_value': 49}]},
   {'date': 'Jan 2015',
    'timestamp': '1420070400',
    'values': [{'query': 'bathroom', 'value': '62', 'extracted_value': 62}]},
   {'date': 'Feb 2015',
    'timestamp': '1422748800',
    'values': [{'query': 'bathroom', 'value': '59', 'extracted_value': 59}]},
   {'date': 'Mar 2015',
    'timestamp': '1425168000',
    'values': [{'query': 'bathroom', 'value': '59', 'extracted_value': 59}]},
   {'date': 'Apr 2015',
    'timestamp': '1427846400',
    'values': [{'query': 'bathroom', 'value': '58', 'extracted_value': 58}]},
   {'date': 'May 2015',
    'timestamp': '1430438400',
    'values': [{'query': 'bathroom', 'value': '55', 'extracted_value': 55}]},
   {'date': 'Jun 2015',
    'timestamp': '1433116800',
    'values': [{'query': 'bathroom', 'value': '61', 'extracted_value': 61}]},
   {'date': 'Jul 2015',
    'timestamp': '1435708800',
    'values': [{'query': 'bathroom', 'value': '63', 'extracted_value': 63}]},
   {'date': 'Aug 2015',
    'timestamp': '1438387200',
    'values': [{'query': 'bathroom', 'value': '64', 'extracted_value': 64}]},
   {'date': 'Sep 2015',
    'timestamp': '1441065600',
    'values': [{'query': 'bathroom', 'value': '57', 'extracted_value': 57}]},
   {'date': 'Oct 2015',
    'timestamp': '1443657600',
    'values': [{'query': 'bathroom', 'value': '60', 'extracted_value': 60}]},
   {'date': 'Nov 2015',
    'timestamp': '1446336000',

In [17]:
parse("Jul 1-4, 2004", default=datetime(2004, 1, 1, 0, 0, 0, 0, tzinfo=tzinfo('GMT')))

datetime.datetime(2004, 7, 1, 20, 4, tzinfo=<datetime.tzinfo object at 0x169c74f70>)